### ISSUE TITLE
Please a readme explaining what this does, and maybe where it is used.

### ISSUE THREAD

**Issue by nisommer** [epfl-lasa/robot-kinematics#1]

**Comment by sinamr88** [comment]
There are two examples in the packages. Furthermore, another example is "inverse-kinematics-examples".

**Comment by nisommer** [comment]
What I mean is to write a self-explanatory readme.md that we can see when we browse the repository and we can know immediately what the package is doing.
For instance felix has written a nice one for some of his repos:
https://github.com/felixduvallet/allegro_hand_ros
You don't need to make it long, but I still don't know what the package is doing with its current description.

Mostly why do we need this package for (it's probably used by examples or something, but otherwise it's a bit confusing why it's here).

Otherwise if we add lots of repos to epfl-lasa and we don't know what they do it will become quickly messy.

**Comment by felixduvallet** [comment]
I agree with Nicolas; at the minimum a helpful README would specify:
- the purpose of the package: why anyone would want to use this code, what
  functionality the code provides, etc...
- the dependencies, if any
- how to get up and running on a minimal working example: compile & run
  instructions.

Felix

**Comment by sinamr88** [comment]
Me too!
I will write a read-me next week..:)

**Comment by felixduvallet** [comment]
friendly reminder :)

**Comment by sinamr88** [comment]
I've already remembered it!...I am very busy with other stuff....
